version: "3"

services:
  chatgpt-discord-bot:
    build: .
    image: chatgpt-discord-bot
    container_name: chatgpt-discord-bot
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./game_subscriptions.json:/DiscordBot/game_subscriptions.json
      - ./gpt5_settings.json:/DiscordBot/gpt5_settings.json
      - ./audio_cache:/DiscordBot/audio_cache